//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmlDiagramsTest.Properties
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmlDiagramsTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew-&gt;China: Says Hello
        ///Note right of China: China thinks\nabout it
        ///China--&gt;Andrew: How are you?
        ///Andrew-&gt;&gt;China: I am good thanks!.
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: Here is a title
        ///A-&gt;B: Normal line
        ///B--&gt;C: Dashed line
        ///C-&gt;&gt;D: Open arrow
        ///D--&gt;&gt;A: Dashed open arrow.
        /// </summary>
        internal static string Example1 {
            get {
                return ResourceManager.GetString("Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Example of a comment.
        ///Note left of A: Note to the\n left of A
        ///Note right of A: Note to the\n right of A
        ///Note over A: Note over A
        ///Note over A,B: Note over both A and B&quot;.
        /// </summary>
        internal static string Example2 {
            get {
                return ResourceManager.GetString("Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participant C
        ///participant B
        ///participant A
        ///Note right of A: By listing the participants\n you can change their order.
        /// </summary>
        internal static string Example3 {
            get {
                return ResourceManager.GetString("Example3", resourceCulture);
            }
        }
    }
}
